name: nike_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  iconify_flutter: ^0.0.5
  pinput: ^2.2.31
  flutter_svg: ^1.1.6
  flutter_swipe_action_cell: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/profile_images/
    - assets/images/home_images/
    - assets/icons/
